### ISSUE TITLE
Server assets deleted / replaced for no reason.

### ISSUE THREAD

**Issue by Ascor8522** [LLK/scratch-storage#208] opened 2021-01-09 23:17 UTC
I have no idea for a better place for this issue, but there it is.

One of my project got most of its assets deleted / replaced for no reason. I didn't even went on the project for days, didn't edit it either.

The project ID is 138198909.

The manifest still shows the correct asset hashes for some images, but for the others (most of them), when loaded, the default "asset not found / question mark on grey background" shows up.
![image](https://user-images.githubusercontent.com/17651422/104110491-899b4500-52d8-11eb-91bd-0b0079ac3ac2.png)

You can see must of the ID's got replaced with 8e768a5a5a01891b05c01c9ca15eb6aa (costumes 1 to 6, zero is still as it was before)
https://assets.scratch.mit.edu/internalapi/asset/8e768a5a5a01891b05c01c9ca15eb6aa.svg/get/

It wasn't the case a few days ago tho.

**Comment by apple502j** [comment] 2021-01-10 07:10
Duplicate of LLK/scratch-gui#6484

**Comment by BryceLTaylor** [comment] 2021-01-14 20:38
Closing as duplicate of LLK/scratch-gui#6484

**Closed as completed by BryceLTaylor** 2021-01-14 20:38 UTC
