### ISSUE TITLE
Replace got

### ISSUE THREAD

**Issue by aeons** [LLK/scratch-storage#16] opened 2017-09-06 14:07 UTC
`got` is a wrapper for node's `http` library. It currently does not work at all in an environment of an iOS webview, and the newest version seems to not work in browsers/webpack at all.

I suggest replacing it with something else. In our fork, I have replaced it with `whatwg-fetch` with great success, except the fact that tests fail, since it's a polyfill for browsers (`isomorphic-fetch` is outdated and doesn't allow for the same API across node/browser).

If you want, I can submit a PR with my changes.

**Comment by thisandagain** [comment] 2017-09-06 14:29
100% agreed! We would like to replace all occurrences of `got` with `nets` (which is an isomorphic wrapper on top of `request` and `xhr`). See:
https://github.com/LLK/scratch-vm/pull/585

**Comment by aeons** [comment] 2017-09-06 16:45
Sounds good, will PR tomorrow.

**Comment by gengshenghong** [comment] 2017-09-07 02:23
Got similar issue too! Also plan to replace with xhr way. As you started the worK, i will wait for your good news. Thank you.

**Comment by aeons** [comment] 2017-09-07 07:33
I tried adding nets, which was not really a pleasant experience. It's also a library that hasn't been updated for two years.

I tried adding node-fetch directly and using that, and that seems to work fine, both in the browser, in a web view and in tests. So I guess webpack takes care of making it run in the browser. Would you be interested in a PR replacing got with node-fetch?

**Comment by thisandagain** [comment] 2017-09-07 12:54
Hmm. @rschamp @cwillisf I'd like to normalize our decision here so it makes sense across repos. We are using `request` throughout a large number of repos without issue. I'm happy to move to something else but it should be consistent across all modules of 3.0 and (ideally) across all other projects (www, api, etc.). If we move this repository over to `whatwg-fetch` or `node-fetch` we will have three different HTTP request libraries in 3.0 which is not ideal.

**Comment by rschamp** [comment] 2017-09-07 13:52
@thisandagain I agree that whichever way we go for `scratch-storage`, all other 3.0 repos should follow.

@aeons If all of our other repos didn't already use `request`/`xhr`/`nets`, I think we would be interested in moving to some flavor of `fetch`, but as we are now, it'd be easiest to standardize on `nets`, and consider migrating to `fetch` at another time. Although it hasn't been updated in two years, `nets` is only a wrapper for `xhr` and `request`, which are individually upgradeable.

What was the unpleasantness you experienced with `nets`? Can I help work through the issues you had with it?

**Comment by aeons** [comment] 2017-09-07 15:33
In short, it didn't work. It gave several compilation warnings in webpack and failed to load due to a module requiring `"net"` which does not exist. I didn't try pushing it very much before moving on though.

Besides that, adding the nets requirement added almost 1 MB to the output bundle size.

**Comment by gengshenghong** [comment] 2017-09-08 06:29
@aeons @rschamp @thisandagain I've also tested nets on my side and got similar experience as @aeons mentioned above. However, it is NOT an issue of "nets" library. As @rschamp mentioned, "nets" is really a very simple wrapper around "request" and "xhr" (just a few lines of code), no updates in two years might be OK.

Regarding the issue of "net" not exist as @aeons mentioned, it is caused by configuration issue in webpack by scratch-storage (also in other repos like vm, if I remember). If we use "nets" in scratch-storage, and build it, when import it in scratch-gui, webpack will fail with lots of errors like "net missing", all these libraries are Node modules! The root cause is as below in webpack.config.js of "scratch-storage":

`// Node-compatible
    Object.assign({}, base, {
        target: 'node',
        entry: {
            'scratch-storage': './src/index.js'
        },
        output: {
            library: 'ScratchStorage',
            libraryTarget: 'commonjs2',
            path: __dirname,
            filename: 'dist/node/[name].js'
        }
    })`

You are using "node" as the "target", which means the library is for "node" only, but in scratch-gui, we'll use it in browser and the importing will fail when we are using some libraries like "nets" (which involves some node libraries). The fix is very simple:

`// Web-compatible with commonjs2 library target
    Object.assign({}, base, {
        target: 'web',
        entry: {
            'scratch-storage': './src/index.js'
        },
        output: {
            library: 'ScratchStorage',
            libraryTarget: 'commonjs2',
            path: __dirname,
            filename: 'dist/node/[name].js'
        }
    })`

Just use "web" as target and it works (I've tested in scratch-gui already). I got similar issues before. I think the word "web" and "node" is not well defined in scratch 3.0 repos, maybe we can change it better? For example, 3 targets output:

A. web + umd (called "web-compatible" now)
B. web + commonjs2 (covered by "node-compatible" now)
C. node (commonjs2) (also covered by  "node-compatible" now)

I am not sure whether "require" support multiple entries...As I known, we can only define one "main" field in package.json, if we want to import the scratch-storage in both node and web, above webpack.config.js make it work for scratch-gui, but then "npm run tap" in scratch-storage will fail as it is node environment....anyone knows about how to handle it well to make it usable(by web) and testable (by node)?

Hope it helps.

Thanks,
Shenghong

**Comment by gengshenghong** [comment] 2017-09-08 06:53
Maybe we need something like this:

https://stackoverflow.com/questions/40053344/npm-multiple-entry-points

We may need something like:
var storage = require('scratch-storage/dist/web-commonjs2') in `scratch-gui`
var storage = require('scratch-storage/dist/node') in `node` environment like `test/integration/download-known-assets.js`

In my opinion, making web + commonjs2 as the default main entry is ok enough, in `test`, we can easily change below code to another target:
const ScratchStorage = require('../../dist/node/scratch-storage');

If people want to use `scratch-storage` in another node-based project, he should know how to import it correctly (something like require('scratch-storage/nodestuff...')).

Thanks,
Shenghong

**Comment by gengshenghong** [comment] 2017-09-08 07:19
@aeons @thisandagain @rschamp I've just submitted a PR for reference. We may discuss based on the code directly. If this is accepted, other repos like `scratch-vm` (which also use 'node' as 'target' to generate commonjs2 library) may also need to change (to avoid similar issues in future).

**Comment by aeons** [comment] 2017-09-08 08:28
That sounds reasonable. I'm not versed enough in how node vs browser interacts to really give any meaningful feedback though.

**Closed** 2017-09-18 19:49 UTC
Labels: help-wanted
